# 
FROM node:20-alpine 

WORKDIR /usr/src/app

RUN apk update && apk add openssl


COPY package.json package-lock.json turbo.json ./


COPY apps/ ./apps/
COPY packages/ ./packages/

RUN npm install

COPY . .

RUN cd packages/prisma && npx prisma generate  && cd ../..

RUN npm run build


EXPOSE 3001

CMD ["npm", "run", "start-sih"]